Print correct exception when keys cannot be created
Now we get:

  error: Directory '/homeless-shelter/.s3lib-keys' could not be created

instead of:

  error: null